# Generated by Django 4.2.9 on 2024-01-09 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialnex', '0002_post_alter_profile_profileimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profileimg',
            field=models.ImageField(default='default.jpg', upload_to='profile_images'),
        ),
    ]
