# Generated by Django 4.2.9 on 2024-01-10 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialnex', '0003_alter_profile_profileimg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like_Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(max_length=500)),
                ('username', models.CharField(max_length=100)),
            ],
        ),
    ]
